spring:
  datasource:
    url: jdbc:mysql://localhost:3306/travel
    username: root
    password:
    driverClassname: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl:
          auto: none
