package com.travel.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AboutUsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAboutUsAllPropertiesEquals(AboutUs expected, AboutUs actual) {
        assertAboutUsAutoGeneratedPropertiesEquals(expected, actual);
        assertAboutUsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAboutUsAllUpdatablePropertiesEquals(AboutUs expected, AboutUs actual) {
        assertAboutUsUpdatableFieldsEquals(expected, actual);
        assertAboutUsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAboutUsAutoGeneratedPropertiesEquals(AboutUs expected, AboutUs actual) {
        assertThat(expected)
            .as("Verify AboutUs auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAboutUsUpdatableFieldsEquals(AboutUs expected, AboutUs actual) {
        assertThat(expected)
            .as("Verify AboutUs relevant properties")
            .satisfies(e -> assertThat(e.getDescription()).as("check description").isEqualTo(actual.getDescription()))
            .satisfies(e -> assertThat(e.getContactDetails()).as("check contactDetails").isEqualTo(actual.getContactDetails()))
            .satisfies(e -> assertThat(e.getAdditionalInfo()).as("check additionalInfo").isEqualTo(actual.getAdditionalInfo()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAboutUsUpdatableRelationshipsEquals(AboutUs expected, AboutUs actual) {}
}
