package com.travel.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AgencyServiceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgencyServiceAllPropertiesEquals(AgencyService expected, AgencyService actual) {
        assertAgencyServiceAutoGeneratedPropertiesEquals(expected, actual);
        assertAgencyServiceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgencyServiceAllUpdatablePropertiesEquals(AgencyService expected, AgencyService actual) {
        assertAgencyServiceUpdatableFieldsEquals(expected, actual);
        assertAgencyServiceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgencyServiceAutoGeneratedPropertiesEquals(AgencyService expected, AgencyService actual) {
        assertThat(expected)
            .as("Verify AgencyService auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgencyServiceUpdatableFieldsEquals(AgencyService expected, AgencyService actual) {
        assertThat(expected)
            .as("Verify AgencyService relevant properties")
            .satisfies(e -> assertThat(e.getTitle()).as("check title").isEqualTo(actual.getTitle()))
            .satisfies(e -> assertThat(e.getIcon()).as("check icon").isEqualTo(actual.getIcon()))
            .satisfies(e -> assertThat(e.getContent()).as("check content").isEqualTo(actual.getContent()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertAgencyServiceUpdatableRelationshipsEquals(AgencyService expected, AgencyService actual) {}
}
